language: python
python:
  #- "3.0.1"
  #- "3.1"
  #- "3.4.10"
  - "3.5"
  - "3.6"
install:
    - "pip install pytest"
    - "pip install pytest-cov" #This plugin produces coverage reports
    #- "pip install pytest-xdist" #For distributed testing support install pytest-xdist
script:
  # Problem 1
  #- python -m pytest Problem_1/tests/ # run unit tests with pytest
  - pytest --cov-report term-missing --cov=hello-world hello-world/hello_world_test.py  # check test coverage with pytest-cov