version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
    steps:
      - run:
        name: Exercism Python Track
        command: |  # use pipenv to install dependencies
          sudo pip install pipenv
          pipenv install
          pipenv run pytest